.env.example, index.handlebars, index.html, package-lock.json, package.json, src/app.js, src/style/style.css, webpack.config.js
Closes #12 
- Google API key separated and added to an environment file.
- Handlebars and dot-env plugins/modules added to web pack for assistance.
QA:
[  ] Verify that the server runs without error.
=> Issue 1 service worker

index.html, js/main/index.js, js/main/indexController.js, js/polyfills/promise.js, js/polyfills/url.js, js/sw/index.js, js/utils/loadScripts.js, src/app.js
Service worker has been added and it caches main/index.js and the src/styles/style.css
=> Service worker

.env.example, src/app.js, src/component/geolocation.js, src/component/weather.js
What issue does it solve?
#17 
What did you do to solve the issue?
- User will be prompted to for browser to use current location
- latitude & longitude are returned
- latitude & longitude are used to call google maps api and return city name
- latitude & longitude are used to call openweathermap api to get the current temperature
- Details on obtaining a weather api key have been added to the set up wiki page
How can we test this to be sure it works?
- currently the weather and city results can be seen in the console
note: there may need to be some integration related changes once we move to a react framework
=> Issue 17 geolocation weather api

src/App.js, src/components/Header.js, src/components/InitialMap.js, src/services/geolocation.js
##Issue Number: #55 
Creating header component which will grab the geolocation and weather to display in the header. Adding additional error handling. If there are errors returning geolocation/weather or while pending, "welcome" will be displayed in the header.
- [X ] New feature (non-breaking change which adds functionality)
- [ X] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ X] The issue can be closed.
💔Thank you!
=> Issue 55 header component

.env.example, src/index.css
##Issue Number: #55 
Adding fix to remove default margin on the body tag in index.html. This will allow the header to span across the full width of the page instead of having whitespace around the edges. I missed including this in the PR that was recently merged for #55.
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ X] The issue can be closed.
💔Thank you!
=> adding css to remove default body margins

src/components/Header.js.orig, src/components/InitialMap.js, src/services/geolocation.js
Reverts gwg-women/gwg-women-techmakers#73
Reverting the merge as it's breaking change. Map doesn't get loaded with error Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
=> Revert "Bugfix geolocation latency"

src/App.js, src/components/InitialMap.js, src/components/Places.js
Places side bar gets updated based on the user's location.
No
- [X ] New feature (non-breaking change which adds functionality)
- [ X] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
💔Thank you!
=> Modified places to update based on location

src/App.js, src/components/InitialMap.js, src/components/Places.js
#77
Added Markers for each search result
We can talk about adding an info window for current marker
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] The issue can be closed.
💔Thank you!
=> feat: add markers to show location searched places on the map

public/sw.js, src/components/InitialMap.js, src/components/Places.js, src/components/PlacesListItem.js
##Issue Number: 
#84
Undefined Error on Markers and PlaceListItems 
Caught the undefined open_hours error by checking for undefined values we get from the Places API results and fixed it in both initialMaps and placeListingsItem
Also, changed Info Window styling and made it appear on mouseover instead onMouseClick
No
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] The issue can be closed.
Provide a descriptive branch name and once the pull request …
=> Bug Fix for undefined open_hours error 

public/sw.js
#86 
added caching of index.html and styles for offline mode
- [x ] New feature (non-breaking change which adds functionality)
💔Thank you!
=>  add caching in service worker

public/sw.js
#88 
blank page gets shown in offline mode sometimes
No
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ x] The issue can be closed.
💔Thank you!
=> feat: add style.css and bundle.js to the service worker cache

docs/README.md, docs/Setupinstructions.md, docs/contributionguidelines.md
##Issue Number: 62 
Initial set up for wiki pages in dev before pushing to master
- [ X] Bug fix (non-breaking change which fixes an issue)
💔Thank you!
=> wiki changes and new files

public/sw.js, src/App.js
##Issue Number: 90
Our console was logging a lot of things, a lot of the logs were repetitive. Removed some logging and kept a few key items. Please feel free to add back in any necessary logs if they are needed but I think we should try to limit our logging. 
No
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
- [X ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [X ] The issue can be closed.
Provide a descriptive branch name and once the pull request is approved and merged to dev, the …
=> removing excessive console logs

public/index.html, src/App.js, src/components/Header.js, src/components/InitialMap.js
#90 
Cleaned up console by commenting the console.log statements
Got rid of the api error generated by failed request in InitialMap.js
No
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [x ] The issue can be closed.
💔Thank you!
=> fix: remove all console messages and photo error

src/App.js, src/components/Footer.js
##Issue Number: #33 
I may need to revisit this to figure out a better way to retrieve the information from a local file. I could do this via API but the information doesn't change often and maybe it's best to limit API calls. 
for the time being its information is right in its file and can still be easily accessed and edited. Thank you @tanyagupta for helping me with this.
I do not think so.
💔Thank you!
=> Footer with custom contributors and to their account

public/index.html, src/components/Footer.js, src/components/Places.js, src/css/index.css
##Issue Number: #65 #33
This is a very minor PR. The stretched sidebar bugged me so I just applied a quick fix  while I'm working on the other stuff.
I kept getting a console error about a stylesheet and noticed that there was an old one still linked in index.html so I removed that. 
I was still fiddling around with the footer and I still have yet to figure out how to import it from a directory. It stlll keeps reading it as undefined. *sigh* I'll try again later. For now I will work on the CSS.
No real problems but the footer can still be improved with what I mentioned before.  …
=> minor fixes

src/components/InitialMap.js, src/components/PlacesListItem.js, src/css/index.css
#107
got the photo from Google MAps PlacesService and displayed it on the info window
The infoWindow can be styled better
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [x ] The issue can be closed.
💔Thank you!
=>  add photo to infoWindow

src/components/InitialMap.js, src/components/PlacesListItem.js, src/css/index.css
#109
added photo to placeDetails in search Results 
added style to infoWindow
No
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ x] The issue can be closed.
💔Thank you!
=>  add photo to search results

src/App.js, src/components/Description.js, src/components/Header.js
The wiki endpoint was not getting the city name so it was not working. Adding in a fix so that it now works.
No
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [x ] The issue can be closed.
💔Thank you!
=> fixing description to get city name

public/sw.js, src/App.js, src/components/InitialMap.js, src/components/StaticMap.js, src/registerServiceWorker.js
* Cleaned up assets being cached
* Hijack request to static maps and cache the image
* Return static map when MapContainer's props do not load (aka when offline)
* Created a Static Map component
no
💔Thank you!
=> Cache assets and static map and render them when offline.

public/sw.js, src/App.js, src/components/InitialMap.js, src/components/Places.js
#75 Search Box Feature
The map markers and search results list gets updated when the user enters a new search term and clicks submit
We can add a feature where the map bounds all markers , i looked into it but realized that reducing the zoom level was a better option for now. Have commented the map bound code for now to see if we want to implement it.
I would suggest we do this after we get the marker activating when we click on a search result.
- [ x] New feature (non-breaking change which adds functionality)
- [ …
=> Search Box Feature

docs/README.md
=> added contributors link now

docs/README.md
I fixed several typos in the README. 
No.
- [x ] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
💔Thank you!
=> Updated README.md to fix a few typos.

src/App.js
Removed , from import statement which lead to breaking the app
By mistake with PR #119 a comma got added in app.js, which led to a breaking the app. 
To avoid issues for those pulling in the latest I have removed the , from Import statement in App.js
No
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
- [ X] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch. …
=> Minor change in app to avoid breaking the app

docs/README.md, docs/contributors.md
=> updating rest of the files

docs/contributors.md
##Issue Number: 62
Added contrib details
No
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the code style of this project.
💔Thank you!
=> added info on contributors

docs/contributors.md
##Issue Number: 62
Debugged changes
No
- [ X] Bug fix (non-breaking change which fixes an issue)
💔Thank you!
=> corrected bug

docs/contributors.md
##Issue Number: 62
removed number of contributions
No
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
💔Thank you!
=> removed number of contributions

docs/contributors.md
##Issue Number:62
removed JSON links
No
- [X ] Bug fix (non-breaking change which fixes an issue)
💔Thank you!
=> removing json links
